name: Kraken 8H Trend Alert

on:
  schedule:
    - cron: '35 0 * * *'
    - cron: '35 8 * * *'   
    - cron: '35 16 * * *'
  workflow_dispatch:

jobs:
  check_ma_crossover:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt requests pandas python-telegram-bot pytz

      - name: Download Python time script
        run: curl -o time.py ${{ secrets.TIME }}

      - name: Run Telegram message script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python time.py

      - name: Download Python script
        run: curl -o checker.py ${{ secrets.CHECKER }}

      - name: Verify script download
        run: head -n 10 checker.py

      - name: Print current UTC time
        run: date -u

      - name: Run MA crossover check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python checker.py
